project.name=web3
project.version=1.0

# dirs
src.dir=src
main.dir=src/main
test.dir=src/test
build.dir=ant/build
classes=${build.dir}/classes
libs=${build.dir}/libs
web.dir=${main.dir}/webapp
resources.dir=${main.dir}/resources
doc.dir=${build.dir}/doc

# jar-archive
#jar.name=${project.name}.jar
war.name=${project.name}.war

# scp parameters
scp.host=helios.cs.ifmo.ru
scp.port=2222
scp.user=s412939
scp.remote.dir=~

# alt parameters
replace.regex.oldName=ren1kron
replace.regex.newName=Kostya666

# env parameters
env.java.versions=11,17
env.jvm.args=-Xmx512m -ea

# git and svn parameters
git.repo.url=https://github.com/ren1kron/web_lab3.git
#svn.repo.url=https://svn.com/we

# diff parameters
diff.critical.classes=org/ren1kron/FacesConfiguration.java

# music parameters
music.file={resources.dir}/musicfile.mp3
