# project parameters
project.version=1.0.0
scp.server=s412939@helios.cs.ifmo.ru:/home/studs/s412939
music.cmd=vlc /path/to/music.mp3
env.javaVersions=11,17
env.jvmArgs=-Xmx512m
build.dir=target
war.name=lab3-???
music.path=resourses/musicfile.mp3

# for diff
excluded.files=**/SomeService.java,**/AnotherClass.java

# for alt
replace.old.name=MyClass
replace.new.name=MyAltClass
