# project parameters
project.version=1.0.0
scp.server=user@some.server:/home/user/lab3/
music.cmd=vlc /path/to/music.mp3
env.javaVersions=11,17
env.jvmArgs=-Xmx512m

# for diff
excluded.files=**/SomeService.java,**/AnotherClass.java

# for alt
replace.old.name=MyClass
replace.new.name=MyAltClass
