# project parameters
project.version=1.0.0
scp.server=s409411@helios.cs.ifmo.ru:/home/studs/s409411/zalupa
music.cmd=vlc /path/to/music.mp3
env.javaVersions=11,17
env.jvmArgs=-Xmx512m

# for diff
excluded.files=**/SomeService.java,**/AnotherClass.java

# for alt
replace.old.name=MyClass
replace.new.name=MyAltClass
